#+TITLE: DEV NOTEBOOK - README
#+AUTHOR: Benjamin
#+EMAIL: b3nj4m1n@gmx.net
#+LANGUAGE: en

This repository is the home for all of my computer related notes. This includes programming languages, frameworks, etc.

The directory structure is as follows:
#+begin_src shell :results output :exports output :wrap example
tree -P "EXAMPLE.org|README.org"
#+end_src

#+RESULTS:
#+begin_example
.
├── languages
│   └── EXAMPLE.org
└── README.org

1 directory, 2 files
#+end_example

The languages directory contains language specific notes, as well as an =EXAMPLE.org= file, which serves as a blueprint for new languages.

The =LANGUAGE.org= file contains general information, such as *Set-up* instructions, *Snippets* (For when you haven't touched a language in a year and want to quickly refresh your mind on what the syntax looked like; This includes /Reading & Writing from and to stdin, stout & files/, /Common string operations/, /Type conversion/, /Comparisons & Boolean Operators/, /Flow-Control (If, else if, else, while, for, for-each)/, /Importing packages and files/, /Defining and using classes/, /defining and using functions/, /The available primitive data types/ and /data structures/.), *Troubleshooting* (Errors one might encounter and their solutions), and *Frameworks* (Which each can contain a /Set-up/, /Snippets/ and /Troubleshooting/ section.).

When something is written in all caps, that means its a variable which should be replaced.
